name: Update M3U

on:
  schedule:
    - cron: "0 * * * *"   # every 1 hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install yt-dlp
        run: |
          pip install -U yt-dlp

      - name: Run script
        run: |
          chmod +x update_playlist.sh
          ./update_playlist.sh

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add playlist.m3u
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto update"
          git push
